import { Injectable, Logger } from '@nestjs/common';
import { InjectDataSource } from '@nestjs/typeorm';
import { DataSource } from 'typeorm';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { ConfigService } from '@nestjs/config';

/**
 * Replaces the Socket.io server with Supabase Realtime (Postgres CDC).
 *
 * Why:
 *   - Socket.io requires a Redis adapter when scaled horizontally.
 *   - Supabase Realtime streams Postgres changes directly — when a row
 *     is inserted into `notifications`, every connected client in that
 *     school receives the event. Zero custom infrastructure.
 *   - Less code, fewer moving parts, fewer failure modes.
 *
 * Usage in feature modules:
 *   await this.realtime.broadcastToSchool(schoolId, 'notifications:new', payload);
 *
 * On the frontend:
 *   const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
 *   supabase.channel(`school:${schoolId}`)
 *     .on('postgres_changes',
 *         { event: 'INSERT', schema: 'public', table: 'notifications', filter: `school_id=eq.${schoolId}` },
 *         (payload) => console.log('New notification', payload.new))
 *     .subscribe();
 *
 * In dev/test where Supabase isn't configured, falls back to no-op
 * (so tests don't require a running Supabase instance).
 */
@Injectable()
export class RealtimeService {
  private readonly logger = new Logger(RealtimeService.name);
  private client?: SupabaseClient;

  constructor(private readonly config: ConfigService) {}

  onModuleInit() {
    const url = this.config.get<string>('SUPABASE_URL');
    const serviceKey = this.config.get<string>('SUPABASE_SERVICE_ROLE_KEY');

    if (url && serviceKey) {
      this.client = createClient(url, serviceKey, {
        realtime: { params: { eventsPerSecond: 10 } },
      });
      this.logger.log('Supabase Realtime client initialised');
    } else {
      this.logger.warn('SUPABASE_URL/SUPABASE_SERVICE_ROLE_KEY not set — realtime disabled');
    }
  }

  /**
   * Broadcast a custom event to all clients subscribed to a school's channel.
   *
   * Use this for events that aren't simple DB inserts (e.g., "report ready",
   * which is generated by a worker but doesn't write a notifications row).
   *
   * For DB-backed events (announcements, messages, notifications), you can
   * SKIP this entirely — Supabase Realtime auto-broadcasts the INSERT.
   */
  async broadcastToSchool(
    schoolId: string,
    event: string,
    payload: Record<string, unknown>,
  ): Promise<void> {
    if (!this.client) return; // no-op in dev

    try {
      const channel = this.client.channel(`school:${schoolId}`);
      await channel.send({
        type: 'broadcast',
        event,
        payload,
      });
      this.logger.debug(`Broadcast ${event} to school ${schoolId}`);
    } catch (err) {
      this.logger.warn(`Realtime broadcast failed: ${(err as Error).message}`);
    }
  }

  /**
   * Broadcast to a single user (e.g., "your report card is ready").
   */
  async broadcastToUser(
    userId: string,
    event: string,
    payload: Record<string, unknown>,
  ): Promise<void> {
    if (!this.client) return;

    try {
      const channel = this.client.channel(`user:${userId}`);
      await channel.send({
        type: 'broadcast',
        event,
        payload,
      });
    } catch (err) {
      this.logger.warn(`Realtime broadcast to user ${userId} failed: ${(err as Error).message}`);
    }
  }
}
